### ISSUE TITLE
Is it open source?

### ISSUE THREAD

**Issue by xiaozhihao0** [Rock-100/MonoDet#1]
Hello, I have read your paper, which is very helpful to me. Is the code open source?

**Comment by MagicRock100** [comment]
@xiaozhihao0 Yes, the source code will be released later.

**Comment by gujiaqivadin** [comment]
looking forward to see the opne-source code soon!

**Comment by gujiaqivadin** [comment]
@MagicRock100 Hello, we are looking forward to your great work Monorcnn. Could you give a rough date of the release day?
