### ISSUE TITLE
Using model for video stream

### ISSUE THREAD

**Issue by harisgulzar1** [Rock-100/MonoDet#12]
I could get the expected results by testing the model on validation set of KITTI dataset.
How can I use the MonoRCNN for my own video?

As MonoRCNN is built upon a model from detectron, some of the model parameters don't seem to be recognized by Detectron API when I use demo.py with MonoRCNN Configuration.
@Rock-100

**Comment by harisgulzar1** [comment]
@Rock-100 
Any hint on this would be very appreciated.

**Comment by Rock-100** [comment]
Hello @harisgulzar1, sorry for missing the message.

For my video demo, I use a video sequence of the KITTI raw dataset and process it using [this script](https://github.com/Rock-100/MonoDet/blob/main/projects/KITTI/prepare_KITTI.py) The images and intrinsics are available from the KITTI webpage. For your video, I think you could similarly organize it and then test.

I haven't met the second problem before. I think if we train and test the model all using this detection codebase, this should not happen. Could you please provide more information?

**Comment by harisgulzar1** [comment]
Thanks for the information.
I solved the second issue by adding MonoDet configuration from [main.py](https://github.com/Rock-100/MonoDet/blob/main/projects/MonoRCNN/main.py) in [demo.py](https://github.com/Rock-100/MonoDet/blob/main/demo/demo.py)
`add_monodet_config(cfg)` 
And now the problem related to configuration is solved and demo.py works fine for MonoRCNN.
I will look at [prepare_KITTI.py](https://github.com/Rock-100/MonoDet/blob/main/projects/KITTI/prepare_KITTI.py) for preparing a proper demo.
Thanks.
