### ISSUE TITLE
Training on the Waymo dataset

### ISSUE THREAD

**Issue by wbzheng11** [Rock-100/MonoDet#18]
Hello, now I have successfully conducted experiments on the waymo dataset following [data_setup](https://github.com/abhi1kumar/DEVIANT/blob/main/data/data_setup_README.md)

But the experimental results in the paper cannot be reproduced.

For some metrics, it is impossible to achieve the values stated in the paper.

This is the training environment I use:
![image](https://github.com/Rock-100/MonoDet/assets/129859251/c4a04773-65c0-4d7a-b4f9-424b4f1232aa)

In addition, I tested the detection results on waymo you provided in the code：
[Waymo](https://drive.google.com/file/d/1fL3E3yqZbRd3va3kN-1j-1YlX61-Qo13/view?usp=sharing)

It is also impossible to reproduce the results in the paper.

I would like to know if there is an error in the data you uploaded? Can you provide the evaluation script you used to reproduce the results in the paper?

Thank you！

**Comment by Rock-100** [comment]
Hello @wbzheng11 , thanks for your interests!

Please normalize the prediced scores to [0, 1] before evaluation. And the evaluation script I used is here: https://github.com/amazon-science/progressive-coordinate-transforms/tree/main/tools/waymo.

**Comment by SlothGwon** [comment]
can you share us how to normalize the predicted score?

**Comment by Rock-100** [comment]
@SlothGwon 

The formulation is (score - score<sub>min</sub>) / (score<sub>max</sub> - score<sub>min</sub>), where score<sub>min</sub> is the minimum score on the test set and score<sub>max</sub> is the maximum one.
