### ISSUE TITLE
scale = 700   

### ISSUE THREAD

**Issue by wangbingok1118** [Rock-100/MonoDet#9]
https://github.com/Rock-100/MonoDet/blob/ff3da335fde8642de02aabe8fe55987258fc557d/projects/MonoRCNN/lib/dis_head.py#L98

这里有什么依据吗？ 感谢感谢

**Comment by Rock-100** [comment]
1/h may be very small, so the network cannot predict it well. Multiplying 1/h with 700 can make the training more stable. In my experiments, multiplying 1/h with 400, 500, 600, or 700 all work well.
